"""empty message

Revision ID: 2ba83ec2cdac
Revises: 91fdbc549bb6
Create Date: 2024-03-27 15:57:04.964121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba83ec2cdac'
down_revision = '91fdbc549bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dueDate', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('task_description_key', type_='unique')
        batch_op.drop_constraint('task_title_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_unique_constraint('task_title_key', ['title'])
        batch_op.create_unique_constraint('task_description_key', ['description'])
        batch_op.drop_column('dueDate')

    # ### end Alembic commands ###
